const PASSENGER_NAME_MIN_LENGTH = 2;
const PASSENGER_NAME_MAX_LENGTH = 25;

const stripDiacritics = (value) =>
  String(value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

const sanitizePassengerName = (value) => {
  const compact = stripDiacritics(value).replace(/\s+/g, "");
  return compact.replace(/[^A-Za-z0-9]/g, "").slice(0, PASSENGER_NAME_MAX_LENGTH);
};

const buildPassengerError = (message) => {
  const error = new Error(message);
  error.status = 400;
  error.code = "INVALID_PAX_NAME";
  return error;
};

const buildAutoLastName = (roomIndex, passengerIndex) =>
  `R${Number(roomIndex) + 1}P${Number(passengerIndex) + 1}`.slice(0, PASSENGER_NAME_MAX_LENGTH);

const ensureNameLength = ({
  value,
  fieldLabel,
  autoGenerated,
  fallback,
  roomIndex,
  passengerIndex,
}) => {
  if (
    value.length >= PASSENGER_NAME_MIN_LENGTH &&
    value.length <= PASSENGER_NAME_MAX_LENGTH
  ) {
    return value;
  }

  if (autoGenerated) {
    const generated = sanitizePassengerName(
      typeof fallback === "function"
        ? fallback({ roomIndex, passengerIndex })
        : fallback,
    );
    if (generated.length >= PASSENGER_NAME_MIN_LENGTH) {
      return generated.slice(0, PASSENGER_NAME_MAX_LENGTH);
    }
  }

  throw buildPassengerError(
    `${fieldLabel} must be 2-25 letters or numbers with no spaces or special characters.`,
  );
};

const buildNameKey = (firstName, lastName) =>
  `${String(firstName).toLowerCase()}|${String(lastName).toLowerCase()}`;

const ensureUniquePassengerName = ({
  firstName,
  lastName,
  roomIndex,
  passengerIndex,
  autoGenerated,
  registry,
}) => {
  if (!(registry instanceof Set)) {
    return { firstName, lastName };
  }

  const initialKey = buildNameKey(firstName, lastName);
  if (!registry.has(initialKey)) {
    registry.add(initialKey);
    return { firstName, lastName };
  }

  if (!autoGenerated) {
    throw buildPassengerError(
      "Passenger names must be unique per booking (first + last).",
    );
  }

  const baseLast = lastName;
  for (let attempt = 2; attempt <= 999; attempt += 1) {
    const suffix = String(attempt);
    const trimmedBase = baseLast.slice(
      0,
      Math.max(PASSENGER_NAME_MIN_LENGTH, PASSENGER_NAME_MAX_LENGTH - suffix.length),
    );
    const candidateLast = `${trimmedBase}${suffix}`.slice(0, PASSENGER_NAME_MAX_LENGTH);
    const candidateKey = buildNameKey(firstName, candidateLast);
    if (!registry.has(candidateKey)) {
      registry.add(candidateKey);
      return { firstName, lastName: candidateLast };
    }
  }

  throw buildPassengerError(
    `Unable to generate a unique passenger name for room ${Number(roomIndex) + 1}, passenger ${Number(passengerIndex) + 1}.`,
  );
};

export const normalizePassengerIdentity = ({
  passenger = {},
  roomIndex = 0,
  passengerIndex = 0,
  registry = null,
}) => {
  const autoGenerated = Boolean(passenger?.autoGenerated);

  const firstNameRaw =
    passenger?.firstName ??
    passenger?.givenName ??
    null;
  const lastNameRaw =
    passenger?.lastName ??
    passenger?.surname ??
    null;

  const firstNameSanitized = sanitizePassengerName(firstNameRaw);
  const lastNameSanitized = sanitizePassengerName(lastNameRaw);

  const firstName = ensureNameLength({
    value: firstNameSanitized,
    fieldLabel: "Passenger firstName",
    autoGenerated,
    fallback: "Guest",
    roomIndex,
    passengerIndex,
  });

  const lastName = ensureNameLength({
    value: lastNameSanitized,
    fieldLabel: "Passenger lastName",
    autoGenerated,
    fallback: ({ roomIndex: rIdx, passengerIndex: pIdx }) =>
      buildAutoLastName(rIdx, pIdx),
    roomIndex,
    passengerIndex,
  });

  return ensureUniquePassengerName({
    firstName,
    lastName,
    roomIndex,
    passengerIndex,
    autoGenerated,
    registry,
  });
};

export const markAutoGeneratedPassenger = (passenger = {}) => ({
  ...passenger,
  autoGenerated: true,
});
